on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache-dependency-path: "go.sum"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Build image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/aspiand/lego:latest